services:
  ollama:
    image: ollama/ollama:${OLLAMA_DOCKER_TAG:-latest}
    container_name: ollama
    pull_policy: always
    ports:
      - ${OLLAMA_PORT:-11434}:11434
    volumes:
      - ./ollama:/root/.ollama
    environment:
      OLLAMA_MAX_LOADED_MODELS: ${OLLAMA_MAX_LOADED_MODELS:-1}
      OLLAMA_NUM_PARALLEL: ${OLLAMA_NUM_PARALLEL:-1}
      OLLAMA_SCHED_SPREAD: ${OLLAMA_SCHED_SPREAD:-0}
      OLLAMA_FLASH_ATTENTION: ${OLLAMA_FLASH_ATTENTION:-1}
      OLLAMA_KV_CACHE_TYPE: ${OLLAMA_KV_CACHE_TYPE:-q8_0}
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: always

  open-webui:
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG:-main}
    container_name: open-webui
    volumes:
      - ./open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - ${OPEN_WEBUI_PORT:-3000}:8080
    environment:
      OLLAMA_BASE_URL: http://ollama:11434
      ENABLE_SIGNUP: true
    restart: always
